### ISSUE TITLE
Feature request: coordinator init / debugging

### ISSUE THREAD

**Issue by fwolfst** [patience4711/read-APSystems-YC600-QS1-DS3#116]
Impressed that there are still many improvements going on!

In my try to implement the minimal functionality (coordinator, pairing, polling) in a C++ API, I am struggling with the polling. Everything before seems to be fine, but I get the wrong answers (AF_DATA_REQUEST or AF_DATA_CONFIRM missing, answer too short).

I compared the commands sent from your and my code byte by byte. Sometimes the answers differ minimally, which I guess is normal (still they include e.g. the ecu id). The only commands which I could not debug very well over the console was the coordinator initialization (because there is no command for it).

I would have two feature requests:
1) add a command to re-init the whole zigbee system/coordinator, e.g. 10;ZBRESTART (btw, why always `10; ...`?)
2) make the web-console "endless" if wanted, because I try to copy the commands over and have to be quick.

I would try to implement it myself, but even if I make all the changes to get it compiling under Linux, it will crash fast :(

Thanks for considering and keeping this project so alive!

**Comment by patience4712** [comment]
@fwolfst You can type 10;INIT_N to restart the zigbee system.  10; is to make it difficult.... As for your other question, the console output can influence the timing of the commands so i rather not touch it now it works oke. if you toggle diag you may have more time to copy. 

I give you a hint. When you issue the 2700 command you get an answer the says (or not) that the coordinator is up. It can however be in a state then that it never gets polling answers. I had that with the esp32 where i used commands made with snprintf.  I suspect that is is not due to the last (normal operations) command. Could be a command with empty space at the end or something. The confusing thing is that this doesn't disturb the pairing.  This is why i do things as i do them. Hope that this helps.
