### ISSUE TITLE
ESP32-ECU

### ISSUE THREAD

**Issue by patience4711** [patience4711/read-APSystems-YC600-QS1-DS3#95]
Inspired by the stablility problems that sometimes arise when > 5 inverters are defined i have ported the software to an ESP32. This soc has more memory so it should be able to handle more inverters.
Furthermore there are multiple serial ports so we can get serial debug info on the serial monitor while using the other port for the zigbee (tx=pin17 , rx=pin16 .  The webconsole can avoided because we can issue commands via the serial monitor. This means that without websockets, the webserver is relieved.

So far what i have tested is that it sends the commands to bring the coordinator up, the pair commands and the poll command correctly. With the zigbee connected, the coordinator is brought up correctly. So the processes to pair and poll the inverters should work. 

I made a separate repo for this project, you can visit this [here](https://github.com/patience4711/ESP32-read-APS-inverters)

![esp32front](https://user-images.githubusercontent.com/12282915/228917805-a0cbe4d1-26fa-44cf-84e3-c530bbdbb625.jpg)

**Comment by joffito** [comment]
How cool is that?! Be prepared for a huge feature request list :-). I only have 1 inverter and 2 panels. but two systems at different locations. i am thinking now to sell my ECU B which i have in 1 of the locations and build another system based on the ESP32 just to test it.

**Comment by Superbert25** [comment]
I will try the ESP32 version as soon as I have an ESP32 board available (ordered it yesterday) and some time to build a test setup.
Thanks for your effort!
R.
Eeg.

**Comment by JanBoos** [comment]
I have flashed my esp32 wroom32 with the firmware. It comes up and works fine (wifi, MQTT, time). Only the console is not working:  ERROR this link is invalid, go back <--

Futhermore i have bought a zigbee CC2531 and have flashed it with TI smartRF programmer. I dont know if it went right. There is no green light at the end. Futhermore I can't test it because the console is not working.

Overall the esp32 ecu can't start the zigbee:

<html>
<body>


15-12:13:59 | zigbee | starting ZB coordinator failed
-- | -- | --
15-12:13:45 | zigbee | ZBmodule hard reset
15-12:13:44 | zigbee | zb down, received : FE00270027
15-12:13:40 | system | time retrieved
1-0:0:11 | zigbee | initial healthcheck
1-0:0:7 | mqtt | connected
1-0:0:7 | system | boot up


</body>
</html>

**Comment by patience4711** [comment]
Thank you for your interest in my software. If you have problems with the ESP32-ECU, there is a repo for it where you can open an issue. First please read the Wiki, the answers to all questions are there.

**Comment by patience4711** [comment]
Currently we are testing with 1 DS3-L and its working fine.
